source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'FHPushDemo.xcodeproj'
platform :ios, '7.0'

# tobe removed once PR merged in master + 1.1.0-beta2 is pushed to cocoapods
pod 'AeroGear-Push', :git => 'git@github.com:corinnekrych/aerogear-ios-push.git', :branch => 'plist.configurable' 
pod 'FH', :path => '../../'

